---
- name: 'create security group'
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keypair: key-ansible
    region: us-east-1
  tasks:
  - name: 'create security group'
    ec2_group:
      name: groupsBoticario
      description: Allow HTTP and SSH Services
      profile: default
      region: "{{ region }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
    register: ec2_group
  - name: 'Exit'
    debug:
        var: ec2_group
